# Generated by Django 3.0.5 on 2020-05-01 01:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='char_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentRoom',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=100),
        ),
        migrations.CreateModel(
            name='World_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('limit', models.IntegerField(default=501)),
                ('seed', models.TextField(default=None, null=True)),
                ('coords', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventure.Room')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='currentWorld',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.World_Model'),
        ),
    ]
