# Generated by Django 3.0.5 on 2020-05-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200430_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_model',
            name='seed',
            field=models.TextField(default=None, null=True),
        ),
    ]
