# Generated by Django 3.0.5 on 2020-05-01 00:53

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200430_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_model',
            name='coords',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
