# Generated by Django 3.0.5 on 2020-05-01 01:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200430_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_model',
            name='coords',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
