# Generated by Django 3.0.5 on 2020-05-01 01:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20200430_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_model',
            name='coords',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
