# Generated by Django 3.0.5 on 2020-05-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200430_2048'),
        ('adventure', '0006_auto_20200430_2046'),
    ]

    operations = [
    ]
