# Generated by Django 3.0.5 on 2020-05-01 01:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_merge_20200430_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world_model',
            name='coords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
